### ISSUE TITLE
make load doesn't work on ui-patterns

### ISSUE THREAD

**Issue by adrianbrink** [roosmaa/bolos-rs#1]
This works wonderfully for `hello-world`. Yet for `ui-patterns` running `make load` gives me this error:

```
(ledger-rs) ➜  ui-patterns git:(master) ✗ make load
cat: ../customCA.key: No such file or directory
cargo build --release
    Finished release [optimized] target(s) in 0.09s
arm-none-eabi-objcopy -O ihex -S ../target/thumbv6m-none-eabi/release/ui-patterns ../target/thumbv6m-none-eabi/release/ui-patterns.hex
python -m ledgerblue.loadApp \
                 \
                --targetId 0x31100003 \
                --tlv --delete \
                --fileName ../target/thumbv6m-none-eabi/release/ui-patterns.hex \
                --appName "Demo" \
                --appVersion 0.0.0 \
                --dataSize 0 \
                --icon 0100000000ffffff00ffffffffffffffffffff1ffe9ffc9ffc1ffe9ffd9ff9ffffffffffffffffffff
Generated random root public key : b'04c2d78b61e69d1ceddbef635d4d6b8cef35b562d3fecc288fc82653f9b4697db54bf4a50391efbd92a16ba59e38f9c9924208e7c503cd7b8f2968e0ac1ac0f8d2'
Traceback (most recent call last):
  File "/Users/adrianbrink/.pyenv/versions/3.7.0/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/adrianbrink/.pyenv/versions/3.7.0/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/adrianbrink/.pyenv/versions/ledger-rs/lib/python3.7/site-packages/ledgerblue/loadApp.py", line 114, in <module>
    parser = IntelHexParser(args.fileName)
  File "/Users/adrianbrink/.pyenv/versions/ledger-rs/lib/python3.7/site-packages/ledgerblue/hexParser.py", line 78, in __init__
    zoneData += data[4:4 + count]
TypeError: can only concatenate str (not "bytearray") to str
make: *** [load] Error 1
```

**Comment by roosmaa** [comment]
Yes, the `ledgerblue` python module is more fragile than a wine glass :( at some point down the road I want to replace it with a reliable Rust based alternative.

Looks like the patch file I provided has hardcoded paths to python3.6, but you're working with python3.7 so patching probably failed for you. Will update the patch file and instructions in a second.

**Comment by roosmaa** [comment]
Ok, fixed now. So basically what you want to do with the latest master:

```
$ cd ~/.pyenv/versions/ledger-rs/lib/python3.7/
$ patch -p0 < path/to/bolos-rs/demos/ledgerblue-0.1.19.patch
```
And then `make load` should start working
